{{- if .Values.postgres.exposeExternal }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-external-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
  sessionAffinity: ClientIP
{{- end }}