apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-init-schema
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-schemas
          image: postgres:16
          command:
            - /bin/bash
            - -c
            - |
              until pg_isready -h postgres-service -p 5432 -U planify > /dev/null 2>&1; do
                sleep 2
              done
              psql -h postgres-service -U planify -d planify -q <<EOF
              CREATE SCHEMA IF NOT EXISTS keycloak;
              GRANT ALL PRIVILEGES ON SCHEMA keycloak TO planify;
              EOF
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
  backoffLimit: 5