apiVersion: v1
kind: Service
metadata:
  name: event-manager-service
  namespace: planify-dev
spec:
  type: LoadBalancer
  selector:
    app: event-manager-service
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
